### ISSUE TITLE
Prepare to-do's for team members to review all policies

### ISSUE THREAD

**Issue by beperron** [beperron/CADL-policy#13]
When the policies are complete, please prepare a Basecamp to-do that has each member of the data team to review each policy guide in the repo.  Each member should have their own unique to-do (with a fairly tight turnaround time).  Completion of the to-do should indicate that the team member has read and understands the to-do in the entirety.  Any questions that arise should be raised on Slack in the CADL policy.  Of course, the guides will always be a work in progress, but you can decide at what point you feel like it is at a place for the review and acceptance of policy.

**Comment by ClaytonJY** [comment]
Here's the To-do List for this: https://basecamp.com/2699335/projects/9445218/todolists/32176282

I've made tasks for @beperron, @hereismyname, and @bryanvictor to review the latest draft of what is now `Workflow-Policies.md`, PR #11. 

Will add analogous tasks for the styleguide (#9) following some discussion I've started in `#policy-github`.
