### ISSUE TITLE
Repo name changes

### ISSUE THREAD

**Issue by beperron** [beperron/CADL-policy#15]
We need to change the repo names and associated language from CADL to DataLab ... Can you assist with this process?  I don't quite know the implications of making the changes so any thoughts you have on the matter will be greatly appreciated.

**Comment by ClaytonJY** [comment]
This is an issue larger than just this repo; I've made a Basecamp To-Do list for these changes: https://basecamp.com/2699335/projects/9445218/todolists/32287854
